### ISSUE TITLE
Add devel, tools and tkinter to Python roll

### ISSUE THREAD

**Issue by tcooper** [sdsc/python-roll#1]
Redhat/CentOS provided Python includes python-devel, python-tools and tkinter RPMs which add developer functionality to Python...
#### from python.spec of python-2.6.6-64.el6.src.rpm

``` code=bash
...
%files devel
%defattr(-,root,root, -)
%{pylibdir}/config/*
%exclude %{pylibdir}/config/Makefile
%{_includedir}/python%{pybasever}/*.h
%exclude %{_includedir}/python%{pybasever}/%{_pyconfig_h}
%doc Misc/README.valgrind Misc/valgrind-python.supp Misc/gdbinit
%{_bindir}/python-config
%{_bindir}/python%{pybasever}-config
%{_libdir}/libpython%{pybasever}.so

%files tools
%defattr(-,root,root,755)
%doc Tools/modulator/README.modulator
%doc Tools/pynche/README.pynche
%{site_packages}/modulator
%{site_packages}/pynche
%{_bindir}/smtpd*.py*
%{_bindir}/2to3*
%{_bindir}/idle*
%{_bindir}/modulator*
%{_bindir}/pynche*
%{_bindir}/pygettext*.py*
%{_bindir}/msgfmt*.py*
%{tools_dir}
%{demo_dir}
%{pylibdir}/Doc

%files -n %{tkinter}
%defattr(-,root,root,755)
%{pylibdir}/lib-tk
%{dynload_dir}/_tkinter.so
...
```

Make sure these files get added to Python installation even if we don't provide a separate RPM.

**Comment by jjhayes** [comment]
@tcooper It looks like files from all three of these packages are included with/installed by the python source build-and-install process, e.g.,

```
[root@tscc-3-32 ~]# find /opt/python -name lib-tk
/opt/python/lib/python2.7/lib-tk
[root@tscc-3-32 ~]# rpm -q --whatprovides /opt/python/lib/python2.7/lib-tk
sdsc-python-27-2.7.10-2.x86_64
[root@tscc-3-32 ~]# find /opt/python -name 2to3
/opt/python/bin/2to3
[root@tscc-3-32 ~]# rpm -q --whatprovides /opt/python/bin/2to3
sdsc-python-27-2.7.10-2.x86_64
[root@tscc-3-32 ~]# find /opt/python -name Python.h
/opt/python/include/python3.5m/Python.h
/opt/python/include/python2.7/Python.h
[root@tscc-3-32 ~]# rpm -q --whatprovides /opt/python/include/python2.7/Python.h
sdsc-python-27-2.7.10-2.x86_64
```

Some files from the python-tools RPM (at least) are present in the python sources but not installed, e.g., the pynche subdir, and I don't see a target in the python Makefile that installs them.  We could add a cp to the package Makefile, but I'd be inclined to ignore them unless/until they prove to be needed.

**Comment by tcooper** [comment]
@jjhayes This is old enough I don't remember the source of the issue. Possible it's a response to a question on Rocks mailing list though I can't be sure. Probably fine to ignore at least until next Rocks version of Python roll comes out at which point we can revisit an update of the SDSC python roll.
