### ISSUE TITLE
python roll conflicts with rocks6.2 provided opt-python-27 RPM

### ISSUE THREAD

**Issue by akrherz** [sdsc/python-roll#2]
Firstly, thank you so much for contributing these awesome rolls to the community!  I feel like a child in a candy store seeing everything I need :)

I am wondering though how this roll is supposed to coexist with the Rocks 6.2 provided `opt-python-27` RPM.  Are there extra steps needed to first remove that package before installing this roll or are the conflicts between the packages harmless?  I haven't tried deploying this on a cluster node yet...

```
# rpm -qf /opt/python/lib/python2.7/site-packages/numpy/core/info.py
opt-numpy-27-1.8.0-1.x86_64
sdsc-python-27-2.7.10-2.x86_64
```

Thank you!

**Comment by jjhayes** [comment]
Glad to hear that you're finding the SDSC rolls useful.  The SDSC python-roll is a replacement for the python roll found on the rocksclusters website--it started out as a fork from that roll--which is where the opt-python-27 rpm comes from.  You'll definitely encounter collisions if you install both rolls.  I'm unsure to what extent these might be harmless; at least some of the packages in the sdsc python-roll install newer software versions than those found in the rocksclusters roll.

Jim

**Comment by akrherz** [comment]
Oh wow, your explanation is rather obvious now :/  I went down this path as I needed cython to get the `hdf-roll` to build.  Anyway, hopefully your kind response helps somebody else in the future :)
